"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { useState } from "react";

const metadata = {
  title: "Prayag Bhimani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  return (
    <html lang="en">
      <body>
        <Navbar
          isMobileNavOpen={mobileNavOpen}
          setMobileNavOpen={setMobileNavOpen}
        />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
